language: python
python:
  - '2.7'
  - '3.6'

install:
  - pip install -r requirements-test.txt
  - pip install coveralls

script:
  - coverage run setup.py test

after_success:
  - coverage report -m
  - coveralls
